name: SimpleSell
main: rxduz\simplesell\Main
api: 5.23.0
version: 0.0.1
author: "iRxDuZ"

permissions:
  sell.command:
    default: true
  adminsell.command:
    default: true
  adminsell.command.additem:
    default: op
  adminsell.command.edititem:
    default: op
  adminsell.command.removeitem:
    default: op
